import Script from 'next/script';
import "./globals.css"; // globals.css를 import 합니다.

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const KAKAO_MAP_APP_KEY = "bc99ac00ed0c9d2d3419f2bfcd28acc2"; // 실제 JavaScript 키로 변경해주세요

  return (
    <html lang="ko">
      <body className="h-screen">
        {children}
        <Script
          src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${KAKAO_MAP_APP_KEY}&autoload=false`}
          strategy="beforeInteractive"
        />
      </body>
    </html>
  );
}